export const ELEMENTS = {
    inputName: 'input[name="name"]',
    inputCPF: 'input[name="cpf"]',
    inputEmail: 'input[name="email"]',
    inputWhatsapp: 'input[name="whatsapp"]',
    inputPostalcode: 'input[name="postalcode"]',
    buttonCep: 'input[type=button][value="Buscar CEP"]',
    inputAdress: 'input[name="address"]',
    inputAddressNumber: 'input[name="address-number"]',
    inputAddressDetails: 'input[name="address-details"]',
    inputDistrict: 'input[name="district"]',
    inputCityUf: 'input[name="city-uf"]',
    inputImage: 'input[accept^="image"]',
    deliveryMoto: 'img[alt="Moto"]',
    deliveryBicicleta: 'img[alt="Bicicleta"]',
    deliveryCarro: 'img[alt="Van/Carro"]',
    buttonRegister: '.button-success',
    messageSuccess: '#swal2-html-container',
    buttonConfirm: '.swal2-confirm',
    messageNameRequired: 'input[name="name"] + .alert-error',
    messageCPFerror: 'input[name="cpf"] + .alert-error',
    messageEmailRequired: 'input[name="email"] + .alert-error',
    messageCEPRequired: 'input[name="postalcode"] + .alert-error',
    messageAddressNumberRequired: 'input[name="address-number"] + .alert-error',
    messageDeliveryRequired: '.delivery-method + .alert-error',
    messageCNHRequired: '.dropzone + .alert-error'
}